# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicate < Formula
  desc "Streaming replication for SQLite databases"
  homepage "https://github.com/hanzoai/replicate"
  version "0.9.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.3/replicate-0.9.3-darwin-x86_64.tar.gz"
      sha256 "056a8d03c056d8f808b7e263372dff758a472f503390623c8dfa869fbb655fea"

      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.3/replicate-0.9.3-darwin-arm64.tar.gz"
      sha256 "b42daa858240f316ef8ba48f6376242d813b07d9e9bca1fb86eb2ac482f8b32e"

      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.3/replicate-0.9.3-linux-x86_64.tar.gz"
      sha256 "a89560ee4af95ffe8cfcf9c2e87f965c407bee66ae6d3412b2dca91883ab4dde"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.3/replicate-0.9.3-linux-armv6.tar.gz"
      sha256 "1a7d14f1d9c7b8db1e25c8ce5780b0851074c68c965f212215193f4b25568337"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.3/replicate-0.9.3-linux-arm64.tar.gz"
      sha256 "8f80c07d443d8f5b2adac57cdadc8bdd0b3680d741c230abc389df0cf264aab2"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
  end

  test do
    system "#{bin}/replicate", "version"
  end
end
