# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicate < Formula
  desc "Streaming replication for SQLite databases"
  homepage "https://github.com/hanzoai/replicate"
  version "0.9.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.2/replicate-0.9.2-darwin-x86_64.tar.gz"
      sha256 "6df3ac0d39f5d759268bf8ce4fbac7e5dd1a9111d17772dfa5e5764fdbe9760f"

      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.2/replicate-0.9.2-darwin-arm64.tar.gz"
      sha256 "43ff30e43c181ec2c6a28e67f7a08fcd825aaa8d5180b0bf71dde0161233386e"

      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.2/replicate-0.9.2-linux-x86_64.tar.gz"
      sha256 "65f83235dcb0e57f865def1da9f59c895284c33e4912c4bc7afff042e1dc53f3"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.2/replicate-0.9.2-linux-armv6.tar.gz"
      sha256 "bcaea8a1bb344ff6f35c9d5fd8bca55c2bd68b72597d5fca100f54a96aed0f15"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.2/replicate-0.9.2-linux-arm64.tar.gz"
      sha256 "511db08776ec3e9e85e1bb2ba9152120fd24f9811fa2df9377d597e7db22f12c"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
  end

  test do
    system "#{bin}/replicate", "version"
  end
end
