# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Replicate < Formula
  desc "Streaming replication for SQLite databases"
  homepage "https://github.com/hanzoai/replicate"
  version "0.9.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.4/replicate-0.9.4-darwin-x86_64.tar.gz"
      sha256 "e3a75a8a4facdc0ab9c8ac55915aad2b701cf5a72984bda86a193b7c24765cb2"

      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.4/replicate-0.9.4-darwin-arm64.tar.gz"
      sha256 "3e9db64b6e28d8838100ef5985a64e2d4d9f039fa884436ec30ccba7c4e82690"

      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.4/replicate-0.9.4-linux-x86_64.tar.gz"
      sha256 "1ce525991d5a3be1cbe5838611577dc469713e71d73aea6fb0137e3b0db236f9"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.4/replicate-0.9.4-linux-armv6.tar.gz"
      sha256 "a3659a6122bece4a8422dfec66e44bfae23a9b006e68f36e25f3ca17b287ec39"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanzoai/replicate/releases/download/v0.9.4/replicate-0.9.4-linux-arm64.tar.gz"
      sha256 "39407dcef26872fb79482499ee0271d6ec051ab73ac362578e7deff20d0282e4"
      define_method(:install) do
        bin.install "replicate"
        etc.install "etc/replicate.yml" => "replicate.yml"
      end
    end
  end

  test do
    system "#{bin}/replicate", "version"
  end
end
